STATE_TIME_MORNING = 0
STATE_TIME_AFTERNOON = 1
STATE_TIME_EVENING = 2
STATE_TIME_SLEEPING = 3

STATE_DAY_MONDAY = 0
STATE_DAY_TUESDAY = 1
STATE_DAY_WEDNESDAY = 2
STATE_DAY_THURSDAY = 3
STATE_DAY_FRIDAY= 4
STATE_DAY_SATURDAY = 5
STATE_DAY_SUNDAY = 6


STATE_LAST_NOTIFICATION_WITHIN_1HR = 0
STATE_LAST_NOTIFICATION_LONG = 1

ANSWER_NOTIFICATION_DISMISS = 0
ANSWER_NOTIFICATION_IGNORE = 1
ANSWER_NOTIFICATION_ACCEPT = 2
